### ISSUE TITLE
Unable to run gnirehtet

### ISSUE THREAD

**Issue by superdaveace** [Genymobile/gnirehtet#242]
I have just successfully installed gnirehtet but i was unable run gnirehtet . Please see this screenshot: https://ibb.co/SrvxnpY

I've tried on my smartphones but failed: 
- Samsung Galaxy J7+ (Android 7)
- Oppo A3 (Android 8) 
- Vivo Z1 Pro (Android 9)

Any suggestion would be really helpful. 

Kind Regards,

**Comment by rom1v** [comment]
This is fixed on `master`.

See https://github.com/Genymobile/gnirehtet/issues/227

**Comment by superdaveace** [comment]
Thanks for your quick response, i'm not techy person, so sometimes difficult for me to understand here.  

When you said "This is fixed on master." do you mean i need to download & install file "master.zip" ?

I already downloaded & installed this 2 files below but still unable to run gnirehtet.
gnirehtet-rust-win64-v2.3.zip
platform-tools-latest-windows.zip

Btw i followed this instruction on how to install but it seems it doesn't  require to install master.zip
https://www.youtube.com/watch?v=DaQ7eAEqRDw


Please assist me further assistance because i'm a newbie when it comes to this topic.

**Comment by rom1v** [comment]
> When you said "This is fixed on master."

I mean that it is fixed on the development branch, not released yet.

I will probably create a new release soon.

_To be notified, you could click on "Watch" > Releases only in the top bar of GitHub._

**Comment by superdaveace** [comment]
Thanks for your kindness, I really appreciate it.

Do you mind if i ask, when would you release it?
It would be really helpful.

**Comment by rom1v** [comment]
See https://github.com/Genymobile/gnirehtet/issues/227#issuecomment-553581824

**Comment by superdaveace** [comment]
Do you think my devices also contribute the problem? are there list of devices the app doesn't support?

**Comment by rom1v** [comment]
> Do you think my devices also contribute the problem?

This is the very same problem:
> Broadcast completed: result=0

without any dialog.

Just test the version with the fix and tell us if it works for you: https://github.com/Genymobile/gnirehtet/issues/227#issuecomment-553581824
